services:
  postgres:
    restart: always

  bot:
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  observer:
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
