from __future__ import annotations

from datetime import datetime
from typing import Protocol

from bot.domain.models import BankTransferDecision


class SubscriptionRepository(Protocol):
    async def upsert_user(self, user_id: int, username: str | None, first_name: str | None) -> None: ...
    async def get_subscription_expiry(self, user_id: int) -> datetime | None: ...
    async def extend_subscription(self, user_id: int, days: int) -> datetime: ...
    async def revoke_subscription(self, user_id: int) -> None: ...
    async def set_proxy_link(self, proxy_link: str) -> None: ...
    async def get_proxy_link(self) -> str | None: ...
    async def add_payment(
        self,
        user_id: int,
        amount: int,
        currency: str,
        telegram_payment_charge_id: str | None,
        provider_payment_charge_id: str | None,
    ) -> None: ...
    async def get_pending_bank_transfer_request(self, user_id: int) -> int | None: ...
    async def create_bank_transfer_request(self, user_id: int) -> int: ...
    async def approve_bank_transfer_request(self, request_id: int, admin_id: int) -> BankTransferDecision | None: ...
    async def reject_bank_transfer_request(self, request_id: int, admin_id: int) -> BankTransferDecision | None: ...
